# Generated by Django 4.2.3 on 2023-11-12 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('space', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacetaskmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spacetaskmodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='task.spacetaskmodel', verbose_name='Родитель'),
        ),
        migrations.AddField(
            model_name='spacetaskmodel',
            name='responsibles',
            field=models.ManyToManyField(related_name='responsibles', through='task.ResponsibleSpaceTasks', to=settings.AUTH_USER_MODEL, verbose_name='Ответственные'),
        ),
        migrations.AddField(
            model_name='spacetaskmodel',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space', to='space.spacemodel'),
        ),
        migrations.AddField(
            model_name='spacetaskmodel',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status+', to='task.statusmodel'),
        ),
        migrations.AddField(
            model_name='spacetaskmodel',
            name='tags',
            field=models.ManyToManyField(related_name='tags+', through='task.TagSpaceTaskModel', to='task.tagmodel', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='responsiblespacetasks',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_space', to='task.spacetaskmodel', verbose_name='Main задача'),
        ),
        migrations.AddField(
            model_name='responsiblespacetasks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resp_user_space', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AddField(
            model_name='personaltaskmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personaltaskmodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='task.personaltaskmodel', verbose_name='Родитель'),
        ),
        migrations.AddField(
            model_name='personaltaskmodel',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status+', to='task.statusmodel'),
        ),
        migrations.AddField(
            model_name='personaltaskmodel',
            name='tags',
            field=models.ManyToManyField(related_name='tags+', through='task.TagPersonalTaskModel', to='task.tagmodel', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='historicalspacetaskmodel',
            name='author',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalspacetaskmodel',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='task.spacetaskmodel'),
        ),
        migrations.AddField(
            model_name='historicalspacetaskmodel',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalspacetaskmodel',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='task.spacetaskmodel', verbose_name='Родитель'),
        ),
        migrations.AddField(
            model_name='historicalspacetaskmodel',
            name='space',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='space.spacemodel'),
        ),
        migrations.AddField(
            model_name='historicalspacetaskmodel',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='task.statusmodel'),
        ),
        migrations.AlterUniqueTogether(
            name='tagspacetaskmodel',
            unique_together={('task', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='tagpersonaltaskmodel',
            unique_together={('task', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='responsiblespacetasks',
            unique_together={('task', 'user')},
        ),
    ]
