# Generated by Django 4.2.3 on 2023-10-06 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0003_alter_subpersonaltasksm2m_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subspacetasksm2m',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subspacetasksm2m',
            name='subtask',
        ),
        migrations.RemoveField(
            model_name='subspacetasksm2m',
            name='task',
        ),
        migrations.RemoveField(
            model_name='personaltaskmodel',
            name='subtasks',
        ),
        migrations.RemoveField(
            model_name='spacetaskmodel',
            name='subtasks',
        ),
        migrations.AddField(
            model_name='historicalspacetaskmodel',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='task.spacetaskmodel', verbose_name='Родитель'),
        ),
        migrations.AddField(
            model_name='personaltaskmodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='task.personaltaskmodel', verbose_name='Родитель'),
        ),
        migrations.AddField(
            model_name='spacetaskmodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='task.spacetaskmodel', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='personaltaskmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spacetaskmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tagpersonaltaskmodel',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='task.tagmodel', verbose_name='Тег (id)'),
        ),
        migrations.AlterField(
            model_name='tagpersonaltaskmodel',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='task.personaltaskmodel', verbose_name='Задача (id)'),
        ),
        migrations.DeleteModel(
            name='SubPersonalTasksM2M',
        ),
        migrations.DeleteModel(
            name='SubSpaceTasksM2M',
        ),
    ]
