# Generated by Django 4.2.3 on 2023-10-28 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_subspacetasksm2m_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalspacetaskmodel',
            name='created',
            field=models.DateField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalspacetaskmodel',
            name='updated',
            field=models.DateField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personaltaskmodel',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personaltaskmodel',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='spacetaskmodel',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spacetaskmodel',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
