# Generated by Django 4.2.3 on 2023-11-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_historicalspacetaskmodel_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalspacetaskmodel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название задачи'),
        ),
        migrations.AlterField(
            model_name='personaltaskmodel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название задачи'),
        ),
        migrations.AlterField(
            model_name='spacetaskmodel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название задачи'),
        ),
    ]
