# Generated by Django 4.2.3 on 2023-09-16 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_org', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пространство',
                'verbose_name_plural': 'Пространства',
                'db_table': 'Spaces',
            },
        ),
        migrations.CreateModel(
            name='UserSpaceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_space', to='space.spacemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_space', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('space', 'user')},
            },
        ),
        migrations.AddField(
            model_name='spacemodel',
            name='staff',
            field=models.ManyToManyField(related_name='staff', through='space.UserSpaceModel', to=settings.AUTH_USER_MODEL, verbose_name='Персонал'),
        ),
    ]
