# Generated by Django 4.2.3 on 2023-07-14 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgmodel',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelTable(
            name='orgmodel',
            table='Organizations',
        ),
    ]
