# Generated by Django 4.2.3 on 2023-10-05 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramUser',
        ),
    ]
