# Generated by Django 4.2.3 on 2023-10-04 12:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import telegram_django_bot.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('seed_code', models.IntegerField(default=telegram_django_bot.models._seed_code)),
                ('TelegramUsername', models.CharField(blank=True, max_length=64, null=True)),
                ('telegram_language_code', models.CharField(default='en', max_length=16)),
                ('timezone', models.DurationField(default=datetime.timedelta(seconds=10800))),
                ('current_utrl', models.CharField(blank=True, default='', max_length=64)),
                ('current_utrl_code_dttm', models.DateTimeField(blank=True, null=True)),
                ('current_utrl_context_db', models.CharField(blank=True, default='{}', max_length=4096)),
                ('current_utrl_form_db', models.CharField(blank=True, default='{}', max_length=4096)),
                ('user_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_site', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
