# Generated by Django 4.2.3 on 2023-10-04 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usermodel_it_user_alter_usermodel_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='it_user',
        ),
    ]
