# Generated by Django 4.2.3 on 2023-10-06 16:28

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_telegramuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='color',
            field=models.CharField(default='#D7D2D2', help_text='Цвет в HEX-формате', max_length=7, validators=[core.validators.validate_hex], verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='time_zone',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0, 'В пределах России, окей?'), django.core.validators.MaxValueValidator(12, 'В пределах России, окей?')], verbose_name='Часовой пояс'),
        ),
    ]
