# Generated by Django 4.2.3 on 2023-10-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usermodel_color_usermodel_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='avatar',
            field=models.ImageField(default=1, upload_to='avatar/image/', verbose_name='Аватарка'),
        ),
    ]
