# Generated by Django 4.2.3 on 2023-10-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_usermodel_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='avatar',
            field=models.ImageField(default='user/image/default_user.jpg', upload_to='user/image/', verbose_name='Аватарка пользователя'),
        ),
    ]
