# Generated by Django 4.2.3 on 2023-10-26 13:34

import core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_usersocialauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profle', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('time_zone', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0, 'В пределах России, окей?'), django.core.validators.MaxValueValidator(12, 'В пределах России, окей?')], verbose_name='Часовой пояс')),
                ('color', models.CharField(default='#D7D2D2', help_text='Цвет в HEX-формате', max_length=7, validators=[core.validators.validate_hex], verbose_name='Цвет')),
                ('avatar', models.ImageField(default='user/image/default_user.jpg', upload_to='user/image/', verbose_name='Аватарка пользователя')),
            ],
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='color',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='time_zone',
        ),
    ]
