# Generated by Django 4.2.3 on 2023-11-12 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('avatar', models.ImageField(default='space/image/default_space.jpg', upload_to='space/image/', verbose_name='Аватарка пространства')),
            ],
            options={
                'verbose_name': 'Пространство',
                'verbose_name_plural': 'Пространства',
                'db_table': 'Spaces',
            },
        ),
        migrations.CreateModel(
            name='UserSpaceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField(default=False, verbose_name='Избранное')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_space', to='space.spacemodel')),
            ],
        ),
    ]
