# Generated by Django 4.2.3 on 2023-11-12 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspacemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_space', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spacemodel',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_org', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spacemodel',
            name='staff',
            field=models.ManyToManyField(related_name='staff', through='space.UserSpaceModel', to=settings.AUTH_USER_MODEL, verbose_name='Персонал'),
        ),
        migrations.AlterUniqueTogether(
            name='userspacemodel',
            unique_together={('space', 'user')},
        ),
    ]
