# Generated by Django 4.2.3 on 2023-10-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacemodel',
            name='avatar',
            field=models.ImageField(default='space/image/default_space.jpg', upload_to='space/image/', verbose_name='Аватарка пространства'),
        ),
    ]
