# Generated by Django 4.2.3 on 2023-11-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_spacemodel_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspacemodel',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='Избранное'),
        ),
    ]
