# Generated by Django 4.2.3 on 2023-09-24 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_discription_historicalspacetaskmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subpersonaltasksm2m',
            unique_together={('subtask', 'task')},
        ),
        migrations.AlterUniqueTogether(
            name='tagpersonaltaskmodel',
            unique_together={('task', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='tagspacetaskmodel',
            unique_together={('task', 'tag')},
        ),
    ]
