# Generated by Django 4.2.3 on 2023-09-17 04:19

import core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSpaceTaskModel',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('discription', models.TextField(verbose_name='Описание')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Задача пространства',
                'verbose_name_plural': 'historical Задачи пространства',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PersonalTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('discription', models.TextField(verbose_name='Описание')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн')),
            ],
            options={
                'verbose_name': 'Персональная задача',
                'verbose_name_plural': 'Персональные задачи',
                'db_table': 'PersonalTask',
            },
        ),
        migrations.CreateModel(
            name='ResponsibleSpaceTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('discription', models.TextField(verbose_name='Описание')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн')),
            ],
            options={
                'verbose_name': 'Задача пространства',
                'verbose_name_plural': 'Задачи пространства',
                'db_table': 'SpaceTask',
            },
        ),
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название тега', max_length=200, unique=True, verbose_name='Название')),
                ('color', models.CharField(help_text='Цвет в HEX-формате', max_length=7, unique=True, validators=[core.validators.validate_hex], verbose_name='Цвет')),
                ('slug', models.SlugField(help_text='Краткое имя', unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'db_table': 'Status',
            },
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название тега', max_length=200, unique=True, verbose_name='Название')),
                ('color', models.CharField(help_text='Цвет в HEX-формате', max_length=7, unique=True, validators=[core.validators.validate_hex], verbose_name='Цвет')),
                ('slug', models.SlugField(help_text='Краткое имя', unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'db_table': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='TagSpaceTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_space+', to='task.tagmodel', to_field='slug', verbose_name='Тег (id)')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_space+', to='task.spacetaskmodel', verbose_name='Задача (id)')),
            ],
        ),
        migrations.CreateModel(
            name='TagPersonalTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_pers', to='task.tagmodel', to_field='slug', verbose_name='Тег (id)')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_pers', to='task.personaltaskmodel', verbose_name='Задача (id)')),
            ],
        ),
        migrations.CreateModel(
            name='SubSpaceTasksM2M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_task_space', to='task.spacetaskmodel', verbose_name='Sub задача')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_task_space', to='task.spacetaskmodel', verbose_name='Main задача')),
            ],
        ),
        migrations.CreateModel(
            name='SubPersonalTasksM2M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtask', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sub_task_pers', to='task.personaltaskmodel', verbose_name='Sub задача')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_task_pers', to='task.personaltaskmodel', verbose_name='Main задача')),
            ],
        ),
    ]
