# Generated by Django 4.2.3 on 2023-07-22 16:38

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_orgmodel_options_alter_orgmodel_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('discription', models.TextField(verbose_name='Описание')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_task_org', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='organizations.orgmodel')),
            ],
            options={
                'verbose_name': 'Задача организации',
                'verbose_name_plural': 'Задачи организации',
                'db_table': 'OrgTask',
            },
        ),
        migrations.CreateModel(
            name='PersonalTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('discription', models.TextField(verbose_name='Описание')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_task_pers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Персональная задача',
                'verbose_name_plural': 'Персональные задачи',
                'db_table': 'PersonalTask',
            },
        ),
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название тега', max_length=200, unique=True, verbose_name='Название')),
                ('color', models.CharField(help_text='Цвет в HEX-формате', max_length=7, unique=True, validators=[core.validators.validate_hex], verbose_name='Цвет')),
                ('slug', models.SlugField(help_text='Краткое имя', unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'db_table': 'Status',
            },
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название тега', max_length=200, unique=True, verbose_name='Название')),
                ('color', models.CharField(help_text='Цвет в HEX-формате', max_length=7, unique=True, validators=[core.validators.validate_hex], verbose_name='Цвет')),
                ('slug', models.SlugField(help_text='Краткое имя', unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'db_table': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='TagPersonalTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_pers', to='task.tagmodel', to_field='slug', verbose_name='Тег (id)')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_pers', to='task.personaltaskmodel', verbose_name='Задача (id)')),
            ],
        ),
        migrations.CreateModel(
            name='TagOrgTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_org+', to='task.tagmodel', to_field='slug', verbose_name='Тег (id)')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_org+', to='task.orgtaskmodel', verbose_name='Задача (id)')),
            ],
        ),
        migrations.CreateModel(
            name='SubPersonalTasksM2M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtask', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sub_task_pers', to='task.personaltaskmodel', verbose_name='Sub задача')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_task_pers', to='task.personaltaskmodel', verbose_name='Main задача')),
            ],
        ),
        migrations.CreateModel(
            name='SubOrgTasksM2M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_task_org', to='task.orgtaskmodel', verbose_name='Sub задача')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_task_org', to='task.orgtaskmodel', verbose_name='Main задача')),
            ],
            options={
                'unique_together': {('task', 'subtask')},
            },
        ),
        migrations.CreateModel(
            name='ResponsibleOrgTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_org', to='task.orgtaskmodel', verbose_name='Main задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resp_user_org', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'unique_together': {('task', 'user')},
            },
        ),
        migrations.AddField(
            model_name='personaltaskmodel',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status+', to='task.statusmodel', to_field='slug'),
        ),
        migrations.AddField(
            model_name='personaltaskmodel',
            name='subtasks',
            field=models.ManyToManyField(related_name='subtasks+', through='task.SubPersonalTasksM2M', to='task.personaltaskmodel', verbose_name='Подзадачи'),
        ),
        migrations.AddField(
            model_name='personaltaskmodel',
            name='tags',
            field=models.ManyToManyField(related_name='tags+', through='task.TagPersonalTaskModel', to='task.tagmodel', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='orgtaskmodel',
            name='responsibles',
            field=models.ManyToManyField(related_name='responsibles', through='task.ResponsibleOrgTasks', to=settings.AUTH_USER_MODEL, verbose_name='Ответственные'),
        ),
        migrations.AddField(
            model_name='orgtaskmodel',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status+', to='task.statusmodel', to_field='slug'),
        ),
        migrations.AddField(
            model_name='orgtaskmodel',
            name='subtasks',
            field=models.ManyToManyField(related_name='subtasks+', through='task.SubOrgTasksM2M', to='task.orgtaskmodel', verbose_name='Подзадачи'),
        ),
        migrations.AddField(
            model_name='orgtaskmodel',
            name='tags',
            field=models.ManyToManyField(related_name='tags+', through='task.TagOrgTaskModel', to='task.tagmodel', verbose_name='Теги'),
        ),
        migrations.CreateModel(
            name='HistoricalOrgTaskModel',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('discription', models.TextField(verbose_name='Описание')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='task.orgtaskmodel')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.orgmodel')),
                ('status', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='task.statusmodel', to_field='slug')),
            ],
            options={
                'verbose_name': 'historical Задача организации',
                'verbose_name_plural': 'historical Задачи организации',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
