# Generated by Django 4.2.3 on 2023-09-22 14:51

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('space', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('discription', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_task_pers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Персональная задача',
                'verbose_name_plural': 'Персональные задачи',
                'db_table': 'PersonalTask',
            },
        ),
        migrations.CreateModel(
            name='ResponsibleSpaceTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('discription', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_task_space', to=settings.AUTH_USER_MODEL)),
                ('responsibles', models.ManyToManyField(related_name='responsibles', through='task.ResponsibleSpaceTasks', to=settings.AUTH_USER_MODEL, verbose_name='Ответственные')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space', to='space.spacemodel')),
            ],
            options={
                'verbose_name': 'Задача пространства',
                'verbose_name_plural': 'Задачи пространства',
                'db_table': 'SpaceTask',
            },
        ),
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название тега', max_length=200, verbose_name='Название')),
                ('color', models.CharField(help_text='Цвет в HEX-формате', max_length=7, validators=[core.validators.validate_hex], verbose_name='Цвет')),
                ('slug', models.SlugField(help_text='Краткое имя', verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'db_table': 'Status',
            },
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название тега', max_length=200, verbose_name='Название')),
                ('color', models.CharField(help_text='Цвет в HEX-формате', max_length=7, validators=[core.validators.validate_hex], verbose_name='Цвет')),
                ('slug', models.SlugField(help_text='Краткое имя', verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'db_table': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='TagSpaceTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_space+', to='task.tagmodel', verbose_name='Тег (id)')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_space+', to='task.spacetaskmodel', verbose_name='Задача (id)')),
            ],
        ),
        migrations.CreateModel(
            name='TagPersonalTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_pers', to='task.tagmodel', verbose_name='Тег (id)')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_pers', to='task.personaltaskmodel', verbose_name='Задача (id)')),
            ],
        ),
        migrations.CreateModel(
            name='SubSpaceTasksM2M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_task_space', to='task.spacetaskmodel', verbose_name='Sub задача')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_task_space', to='task.spacetaskmodel', verbose_name='Main задача')),
            ],
            options={
                'unique_together': {('task', 'subtask')},
            },
        ),
        migrations.CreateModel(
            name='SubPersonalTasksM2M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtask', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sub_task_pers', to='task.personaltaskmodel', verbose_name='Sub задача')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_task_pers', to='task.personaltaskmodel', verbose_name='Main задача')),
            ],
        ),
        migrations.AddField(
            model_name='spacetaskmodel',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status+', to='task.statusmodel'),
        ),
        migrations.AddField(
            model_name='spacetaskmodel',
            name='subtasks',
            field=models.ManyToManyField(related_name='subtasks+', through='task.SubSpaceTasksM2M', to='task.spacetaskmodel', verbose_name='Подзадачи'),
        ),
        migrations.AddField(
            model_name='spacetaskmodel',
            name='tags',
            field=models.ManyToManyField(related_name='tags+', through='task.TagSpaceTaskModel', to='task.tagmodel', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='responsiblespacetasks',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_space', to='task.spacetaskmodel', verbose_name='Main задача'),
        ),
        migrations.AddField(
            model_name='responsiblespacetasks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resp_user_space', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AddField(
            model_name='personaltaskmodel',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status+', to='task.statusmodel'),
        ),
        migrations.AddField(
            model_name='personaltaskmodel',
            name='subtasks',
            field=models.ManyToManyField(related_name='subtasks+', through='task.SubPersonalTasksM2M', to='task.personaltaskmodel', verbose_name='Подзадачи'),
        ),
        migrations.AddField(
            model_name='personaltaskmodel',
            name='tags',
            field=models.ManyToManyField(related_name='tags+', through='task.TagPersonalTaskModel', to='task.tagmodel', verbose_name='Теги'),
        ),
        migrations.CreateModel(
            name='HistoricalSpaceTaskModel',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('discription', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='task.spacetaskmodel')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='space.spacemodel')),
                ('status', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='task.statusmodel')),
            ],
            options={
                'verbose_name': 'historical Задача пространства',
                'verbose_name_plural': 'historical Задачи пространства',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='responsiblespacetasks',
            unique_together={('task', 'user')},
        ),
    ]
