# Generated by Django 4.2.3 on 2023-09-23 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalspacetaskmodel',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='personaltaskmodel',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='spacetaskmodel',
            old_name='discription',
            new_name='description',
        ),
    ]
