# Generated by Django 4.2.3 on 2023-07-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorgtaskmodel',
            name='deadline',
            field=models.DateTimeField(null=True, verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='orgtaskmodel',
            name='deadline',
            field=models.DateTimeField(null=True, verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='personaltaskmodel',
            name='deadline',
            field=models.DateTimeField(null=True, verbose_name='Дедлайн'),
        ),
    ]
