# Generated by Django 4.2.3 on 2023-07-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_historicalorgtaskmodel_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorgtaskmodel',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='orgtaskmodel',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='personaltaskmodel',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн'),
        ),
    ]
