# Generated by Django 4.2.3 on 2023-09-22 14:03

import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_historicalspacetaskmodel_discription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalspacetaskmodel',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='task.statusmodel'),
        ),
        migrations.AlterField(
            model_name='personaltaskmodel',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status+', to='task.statusmodel'),
        ),
        migrations.AlterField(
            model_name='spacetaskmodel',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status+', to='task.statusmodel'),
        ),
        migrations.AlterField(
            model_name='statusmodel',
            name='color',
            field=models.CharField(help_text='Цвет в HEX-формате', max_length=7, validators=[core.validators.validate_hex], verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='statusmodel',
            name='name',
            field=models.CharField(help_text='Название тега', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='statusmodel',
            name='slug',
            field=models.SlugField(help_text='Краткое имя', verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tagmodel',
            name='color',
            field=models.CharField(help_text='Цвет в HEX-формате', max_length=7, validators=[core.validators.validate_hex], verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='tagmodel',
            name='name',
            field=models.CharField(help_text='Название тега', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tagmodel',
            name='slug',
            field=models.SlugField(help_text='Краткое имя', verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tagpersonaltaskmodel',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_pers', to='task.tagmodel', verbose_name='Тег (id)'),
        ),
        migrations.AlterField(
            model_name='tagspacetaskmodel',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_space+', to='task.tagmodel', verbose_name='Тег (id)'),
        ),
    ]
