# Generated by Django 4.2.3 on 2023-07-14 08:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='telegram_id',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999999999999)], verbose_name='telegram_id'),
        ),
    ]
