# Generated by Django 4.2.3 on 2023-07-22 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usermodel_options_alter_usermodel_email_and_more'),
        ('users', '0005_alter_usermodel_email_alter_usermodel_first_name_and_more'),
    ]

    operations = [
    ]
